### ISSUE TITLE
Same GDrive link of restnet and densenet pretrained model.

### ISSUE THREAD

**Issue by cutun** [guanqj932/AG-CNN-for-Chest-X-ray-Image-Classification#3]
Hi,
I tested only resnet pretrained loading. Also try with old link of densenet but fail as 
KeyError: 'unexpected key "densenet1.features.denseblock1.denselayer1.norm.1.weight" in state_dict'.

And I have a question: Did you oversampling as this dataset imbalance when you training?

**Comment by guanqj932** [comment]
@cutun   Hi, I have updated the resnet and densenet model last night. Please download the model from the new link. Thank you. PS. I do not oversample when training. But I believe the strategies aim to balance the dataset would be important.

**Comment by hksonngan** [comment]
Here the link in Readme.md, look same id for resnet and densenet
3. Download [resnet model](https://drive.google.com/open?id=1I9EIQeWYvDcyN7IGrFZGqCSVzDD652Hz) and [densenet model](https://drive.google.com/open?id=1I9EIQeWYvDcyN7IGrFZGqCSVzDD652Hz). And put it into the logs folder.

**Comment by guanqj932** [comment]
@cutun @hksonngan  Sorry for that. I have checked the link and updated the correct one.

**Comment by hksonngan** [comment]
I try and get this error KeyError: 'unexpected key "densenet1.features.denseblock1.denselayer1.norm.1.weight" in state_dict'

**Comment by guanqj932** [comment]
@hksonngan could you give me much more information,  which test script you used and how you store the download model?

**Comment by guanqj932** [comment]
@hksonngan  It seems like the model file is not matched. But I have tested several times that it works well on my machine. I would test the uploaded codes this time. Will tell you the result. Thank you.

**Comment by somnathrakshit** [comment]
Also, please share the output of pip freeze.

**Comment by guanqj932** [comment]
@hksonngan @cutun  Hi, I download the codes and test on my machine. It is totally good. And now I am not sure what happened.  It is really strange.

**Comment by cutun** [comment]
Hi @guanqj932,
I found the way to load model as convert name in state_dict like this:
```python
from collections import OrderedDict
state_dict_rename = OrderedDict()
for k, v in checkpoint['state_dict'].items():
     if k.find(".1.") > -1:
         name = k.replace(".1.", "1.")
     elif k.find(".2.") > -1:
         name = k.replace(".2.", "2.")
     else:
         name = k
         state_dict_rename[name] = v
```

**Comment by somnathrakshit** [comment]
This happens because of PyTorch version mismatch. Don't think that this model was trained using PyTorch 0.3.1.
